[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
    "dotnet restore",
    "dotnet publish -c Release -o out"
]

[phases.start]
cmd = "cd out && dotnet DecorHaven.API.dll"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

